"""Environment adapter Protocols (no accessibility API).

Five Protocols define the cross-layer contract between the harness and
platform-specific implementations.  All are ``@runtime_checkable``.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Protocol, runtime_checkable

from strata.core.types import AppInfo, CommandResult, Coordinate, FileInfo, ScreenRegion, WindowInfo


@runtime_checkable
class IGUIAdapter(Protocol):
    def click(self, x: float, y: float, button: str = "left") -> None: ...
    def double_click(self, x: float, y: float) -> None: ...
    def move_mouse(self, x: float, y: float) -> None: ...
    def type_text(self, text: str, interval: float = 0.05) -> None: ...
    def press_key(self, key: str) -> None: ...
    def hotkey(self, *keys: str) -> None: ...
    def scroll(self, delta_x: int, delta_y: int) -> None: ...
    def get_screen_size(self) -> tuple[int, int]: ...
    def capture_screen(self, region: ScreenRegion | None = None) -> bytes: ...
    def get_dpi_scale_for_point(self, x: float, y: float) -> float: ...


@runtime_checkable
class ITerminalAdapter(Protocol):
    def run_command(
        self,
        command: str,
        cwd: str | None = None,
        env: Mapping[str, str] | None = None,
        timeout: float = 300.0,
        silence_timeout: float | None = 30.0,
    ) -> CommandResult: ...
    def open_terminal(self, cwd: str | None = None) -> str: ...
    def send_to_terminal(self, session_id: str, text: str) -> None: ...
    def read_terminal_output(self, session_id: str, timeout: float = 1.0) -> str: ...
    def close_terminal(self, session_id: str) -> None: ...


@runtime_checkable
class IFileSystemAdapter(Protocol):
    def read_file(self, path: str) -> str: ...
    def write_file(self, path: str, content: str, encoding: str = "utf-8") -> None: ...
    def list_directory(
        self, path: str, pattern: str | None = None
    ) -> Sequence[FileInfo]: ...
    def move_to_trash(self, path: str) -> str: ...
    def restore_from_trash(self, trash_path: str) -> None: ...
    def get_file_info(self, path: str) -> FileInfo: ...


@runtime_checkable
class IAppManagerAdapter(Protocol):
    def launch_app(
        self, app_name: str, args: Sequence[str] | None = None
    ) -> str: ...
    def close_app(self, app_identifier: str) -> None: ...
    def get_running_apps(self) -> Sequence[AppInfo]: ...
    def switch_to_app(self, app_identifier: str) -> None: ...


@runtime_checkable
class ISystemAdapter(Protocol):
    def get_clipboard_text(self) -> str: ...
    def set_clipboard_text(self, text: str) -> None: ...
    def get_environment_variable(self, name: str) -> str | None: ...
    def set_environment_variable(self, name: str, value: str) -> None: ...
    def get_cwd(self) -> str: ...
    def set_cwd(self, path: str) -> None: ...


@dataclass(frozen=True)
class EnvironmentBundle:
    gui: IGUIAdapter
    terminal: ITerminalAdapter
    filesystem: IFileSystemAdapter
    app_manager: IAppManagerAdapter
    system: ISystemAdapter
